### ISSUE TITLE
Keep audio along with the content here in diarization post

### ISSUE THREAD

**Issue by lepisma** [Vernacular-ai/ml#14]
Audios are using the bucket url which will be made private. @AnirudhDagar let's download the files and keep it here directy.

**Comment by AnirudhDagar** [comment]
Cool! I'll do that. Do you want me to make a PR for the Diarization post, now? Or just the audio files used as examples for now?

**Comment by AnirudhDagar** [comment]
Ohh sorry! It is already done. Thanks!

**Comment by lepisma** [comment]
wait it's not done right? the items are still linked to the s3 bucket. Let's download them and keep here as static files is what i was saying.
